environment: development
port: 8080

openstack:
  auth_url: "http://94.237.83.40/identity/v3"
  username: "admin"
  password: "secret"
  tenant_name: "admin"
  region: "RegionOne"
  domain_name: "default"

terraform:
  working_dir: "/app/terraform"
  state_dir: "/app/terraform/state"
