services:
  backend:
    build:
      context: ..
      dockerfile: ./docker/backend.Dockerfile
    container_name: cloud-provider-backend
    ports:
      - "8080:8080"
    volumes:
      - ../src/backend:/app:cached
      - go-mod-cache:/go/pkg/mod
      - ../src/terraform/clients:/app/terraform/clients
    environment:
      - GIN_MODE=debug
      - CGO_ENABLED=0
    networks:
      - cloud-provider-network
    restart: unless-stopped

volumes:
  go-mod-cache:

networks:
  cloud-provider-network:
    driver: bridge